### ISSUE TITLE
Make interactive mode history persistent

### ISSUE THREAD

**Issue by farshidtz** [canonical/chip-tool-snap#20]
The history in the interactive mode isn't preserved across reboots because the file is written at [`/tmp/chip_tool_history`](https://github.com/project-chip/connectedhomeip/blob/07d0417ec13e82df3480ed18a0a479544d230303/examples/chip-tool/commands/interactive/InteractiveCommands.cpp#L26C59-L26C81) within the snap; which is on `tmpfs`. For preserving the history, the path can be replaced with a persisted one.

The support for interactive mode was added by https://github.com/canonical/chip-tool-snap/pull/19

**Comment by MonicaisHer** [comment]
Installed the chip-tool built from Matter SDK version [e5f5d67](https://github.com/project-chip/connectedhomeip/commit/e5f5d6798ed47706078462f1697c481a8dc60bfa) on ubuntu classic OS:

```
sudo snap install chip-tool --edge
sudo snap connect chip-tool:avahi-observe
sudo snap connect chip-tool:bluez
sudo snap connect chip-tool:process-control
```
Enter interactve mode:
```
$ sudo chip-tool interactive start 
...
>>> pairing onnetwork 110 20202021
>>> onoff toggle 110 1
```
Check that `/tmp/chip_tool_history` no long exists, and it is now located inside the chip-tool snap:
```
$ ls /tmp/chip_tool_history
ls: cannot access '/tmp/chip_tool_history': No such file or directory

$ ls /var/snap/chip-tool/common/mnt/chip_tool_history
/var/snap/chip-tool/common/mnt/chip_tool_history
```

This issue has been fixed by upstream.
