### ISSUE TITLE
Upgrade ZAP version for Matter SDK master branch

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/chip-tool-snap#41]
As the Matter SDK branch has been switched to [master](https://github.com/canonical/chip-tool-snap/blob/main/snap/snapcraft.yaml#L24), the ZAP version is now outdated, leading to [build failures](https://snapcraft.io/chip-tool/builds/2373371) in the edge channel. The ZAP version needs to be updated according to the [MIN_ZAP_VERSION](https://github.com/project-chip/connectedhomeip/blob/master/scripts/tools/zap/zap_execution.py#L26).

**Comment by farshidtz** [comment]
Since https://github.com/project-chip/connectedhomeip/pull/26636, the SDK automatically downloads a compatible ZAP version for arm64.

Moreover, it is recommended to programmatically download the compatible ZAP version by looking into one of [zap.version](https://github.com/project-chip/connectedhomeip/blob/a64773a912e09f65cfe00f527dd8d85123c69c83/scripts/setup/zap.version) or [zap.json](https://github.com/project-chip/connectedhomeip/blob/a64773a912e09f65cfe00f527dd8d85123c69c83/scripts/setup/zap.json), rather than hard cording a version.
